select 
    WHAT_DO_YOU_BELIEVE_IS_YOUR_TECHNICAL_STRENGTH_ as tech_strength,
    WHAT_EXCITES_YOU_THE_MOST_ABOUT_THIS_CAPSTONE_PATHWAY_WHY_ as what_excites_you,
    WHAT_DO_YOU_WANT_TO_BE_TRUE_FOR_YOURSELF_BY_THE_END_OF_CAPSTONE_HOW_DO_YOU_WANT_TO_SEE_YOURSELF_GROW_ as capstone_goals, 
    ANY_ADDITIONAL_THOUGHTS_COMMENTS_ as additional_thoughts, 
    WHICH_PATHWAY_IS_YOUR_TOP_CHOICE_FOR_CAPSTONE_ as pathway_choice, 
    IN_REFLECTION_ON_THIS_LAST_YEAR_WHAT_IS_ONE_MARCY_PROJECT_THAT_YOU_ARE_THE_MOST_PROUD_OF_WHY_WHAT_DID_YOU_INDIVIDUALLY_CONTRIBUTE_TO_THAT_PROJECT_FOR_IT_TO_BE_A_SUCCESS_ as reflection_on_most_proud_project,
    EMAIL_ADDRESS as email
from {{ source('google_sheets', 'raw') }}
